// <auto-generated />
namespace BasicCrud.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usersessionLastActivity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usersessionLastActivity));
        
        string IMigrationMetadata.Id
        {
            get { return "201710221509516_usersessionLastActivity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
